[build]
command = """
rustup install nightly --profile minimal && \
RUSTDOCFLAGS='--cfg=docsrs' cargo +nightly doc --no-deps --features=futures,guide
"""
publish = "target/doc"

[[redirects]]
from = "/*"
to = "/snafu/:splat"
